namespace HomeBudgetViewer.Database.Engine.Restrictions.Categories
{
    public enum Category
    {
        Car,
        Food,
        FoodOutsideTheHome,
        Sport,
        Transport,
        Entertainment,
        Culture,
        Clothes,
        Personal,
        Children,
        Animals,
        Home,
        Phone,
        Internet,
        Electronic,
        Credit,
        Lent,
        Vacation,
        Other,
        Fashion,
        Health,
        Salary,
        Drinking,
        Allowance,
        Bonus,
        PettyCash,
        WonMoney,
        OddJobs,
        PersonalSavings,
        Pension,
        Rent,
        MoneyFromTheSale
    }
}